services:
  server:
    build: .
    ports:
      - 8000:5000
    environment:
      - FLASK_ENV=development

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - server
